---
- name: check for rust installation
  stat: 
    path: ~/.cargo/bin/cargo
  register: cargo

- name: install rust
  when: not cargo.stat.exists
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

- name: rustup update
  shell: rustup update

- name: Install toolchains
  command: rustup install "{{ item }}"
  loop:
    - stable
    - nightly

- name: Install rust binaries
  command: cargo install "{{ item }}"
  loop:
    - zoxide
    - starship
