- name: configure dev environment
  hosts: localhost
  connection: local
  roles:
    - role: apt
      tags:
        - apt
    - role: rust
      tags:
        - rust
    - role: neovim
      tags:
        - neovim
    - role: alacritty
      tags:
        - alacritty
    - role: nerd-fonts
      tags:
        - nerd-fonts
    - role: lazygit
      tags:
        - lazygit
