---
- name: apt update
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 600
  tags:
    - apt

- name: apt install packages
  become: true
  tags:
    - apt
  apt: 
    state: present
    name:
      - git 
      - python3-pip
      - tree
      - curl
      - golang
      - xclip
      - doxygen
      - jq
      - zsh
      - tmux
      - wget
      - curl
      - libssl-dev
      - kitty
      - picom
      - feh
      - fzf
      - stow
      - cmake
      - sway
      - nouveau
      - rofi
      - waybar
      - grim
      - slurp
      - wl-clipboard
