---
- name: apt update
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 600
  tags:
    - apt

- name: apt install packages
  become: true
  tags:
    - apt
  apt:
    state: present
    name:
      - git
      - python3-pip
      - tree
      - curl
      - golang
      - jq
      - zsh
      - tmux
      - wget
      - curl
      - fzf
      - stow
      - cmake
      - protobuf-compiler
      - nouveau-firmware
      - ca-certificates
      - neofetch
      - ripgrep
