---
- name: apt update
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 600
  tags:
    - apt

- name: apt install packages
  become: true
  tags:
    - apt
  apt: 
    state: present
    name:
      - git 
      - python3-pip
      - tree
      - curl
      - golang
      - build-essential
      - cmake
      - nvidia-settings
      - xclip
      - ninja-build
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - g++
      - pkg-config
      - unzip
      - doxygen
      - jq
      - zsh
      - tmux
      - wget
      - curl
      - libssl-dev
      - kitty
      - picom
      - feh
      - fzf
      - i3
      - rofi
      - stow
