---
- name: clone lazygit repo
  git:
    repo: https://github.com/jesseduffield/lazygit.git
    dest: /opt/repos/lazygit
    version: latest
    update: yes
    force: yes

- name: build and install latest lazygit
  become: true
  shell:
    cmd: '{{ item }}'
    chdir: /opt/repos/lazygit
  loop:
   - GOBIN=/usr/local/bin/ go install
