---
- name: install dotfiles
  shell:
    chdir: ~/.dotfiles
    cmd: stow dotfiles -t ~/.config

- name: symlink ~/.config/zsh/.zshrc to ~/.zshrc
  file:
    src: ~/.config/zsh/.zshrc
    dest: ~/.zshrc
    state: link
