---
#  zsh is installed by the apt task
- name: checking if oh-my-zsh has been installed
  stat:
    path: ~/.oh-my-zsh
  register: oh_my_zsh

- name: install oh-my-zsh
  become: true
  become_user: '{{ ansible_user_id }}'
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: oh_my_zsh.stat.exists == False

- name: detecting current shell
  become: true
  become_user: '{{ ansible_user_id }}'
  shell: 'echo $SHELL'
  register: current_shell

- name: make ZSH default shell
  when: "'/bin/zsh' not in current_shell.stdout"
  user:
    name: '{{ ansible_user_id }}'
    shell: /bin/zsh

- name: checking if powerlevel10k has been installed
  stat:
    path: ~/.oh-my-zsh/custom/themes
  register: powerlevel10k

- name: install powerlevel10k
  become: true
  become_user: '{{ ansible_user_id }}'
  when: powerlevel10k.stat.exists == False
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: ~/.oh-my-zsh/custom/themes
    depth: '1'
    update: no
    version: 'master'

    
