---
- name: symbolically link dotfiles
  become: true
  become_user: '{{ ansible_user_id }}'
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  loop:
    - { src: '~/.dotfiles/.zshrc', dest: '~/.zshrc' }
    - { src: '~/.dotfiles/.tmux.conf', dest: '~/.tmux.conf' }
    - { src: '~/.dotfiles/.p10k.zsh', dest: '~/.p10k.zsh'}
    - { src: '~/.dotfiles/alacritty.yml', dest: '~/.config/alacritty/alacritty.yml'}