---
- name: clone neovim repo
  git:
    repo: https://github.com/neovim/neovim.git
    dest: ~/repos/neovim
    version: stable
    update: yes
    force: yes

- name: build and install latest stable neovim
  shell: 
    cmd: '{{ item }}'
    chdir: ~/repos/neovim
  loop:
   - rm -r .deps/
   - rm -r build/
   - make CMAKE_BUILD_TYPE=Release
   - sudo rm -f /usr/local/bin/nvim
   - sudo rm -r /usr/local/share/nvim
   - sudo make install
