---
- name: install neovim dependencies
  become: true
  tags:
    - apt
  apt:
    state: present
    name:
      - ninja-build
      - gettext
      - cmake
      - unzip
      - curl
      - build-essential

- name: clone neovim repo
  git:
    repo: https://github.com/neovim/neovim.git
    dest: ~/repos/neovim
    version: stable
    update: yes
    force: yes

- name: build and install latest stable neovim
  shell: 
    cmd: '{{ item }}'
    chdir: ~/repos/neovim
  loop:
   - rm -r .deps/ || true
   - rm -r build/ || true
   - make CMAKE_BUILD_TYPE=Release
   - sudo rm -f /usr/local/bin/nvim
   - sudo rm -r /usr/local/share/nvim || true
   - sudo make install

- name: install latest nvim plugins
  shell: '{{ item }}'
  loop:
    - nvim --headless "+Lzy! sync" +qa
